users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

projects:
    resource: "@ProjectsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:      /test2
    defaults:  { _controller: AppBundle:Default:test}
